#define SCREEN_WIDTH 640
#define SCREEN_HEIGHT 480


#define MAP_SIZE 96
#define TILE_HEIGHT 30
#define TILE_WIDTH 60
#define MAP_RENDER_SIZE 24
#define MAP_RENDER_OFFSET_X ((SCREEN_WIDTH - (TILE_WIDTH * MAP_RENDER_SIZE)) / 2)
#define MAP_RENDER_OFFSET_Y 425
